#!/bin/sh

set -ex

cp ~/go/env .
cp ~/.tmux.conf .
cp ~/.config/alacritty/alacritty.yml .
cp ~/.config/starship.toml .
cp ~/.config/nvim/init.vim .
cp ~/.config/nvim/coc-settings.json .
echo '# AJG' > .profile      && sed '0,/# AJG/d' ~/.profile >> .profile
echo '# AJG' > .bashrc       && sed '0,/# AJG/d' ~/.bashrc >> .bashrc

