#!/bin/sh

set -ex

cp ~/go/env . || true
cp ~/.config/starship.toml . || true
cp ~/.config/nvim/init.vim . || true
echo '# AJG' > .profile      && sed '0,/# AJG/d' ~/.profile >> .profile
echo '# AJG' > .bashrc       && sed '0,/# AJG/d' ~/.bashrc >> .bashrc

