#!/bin/sh

cp .tmux.conf ~/.tmux.conf .
cp alacritty.yml ~/.config/alacritty/alacritty.yml .
cp starship.toml ~/.config/starship.toml .
cp init.vim ~/.config/nvim/init.vim .
cp coc-settings.json ~/.config/nvim/coc-settings.json .
cat .bashrc  >> ~/.bashrc
cat .profile >> ~/.profile
cat .bash_profile >> ~/.bash_profile

yay -S go nerd-fonts-hack tmux ripgrep fd neovim google-chrome nodejs docker steam visual-studio-code-bin cmake
yay -Rsn firefox
usermod -aG docker $(whoami)

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
cargo install alacrity starship bottom proximity-sort gitui

git clone https://github.com/alacritty/alacritty.git && cd alacritty && \
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg && \
sudo desktop-file-install extra/linux/Alacritty.desktop && \
sudo update-desktop-database && \
cd .. && rm -rf alacritty 

git config --global init.defaultBranch main
git config --global user.email ajguerrer@gmail.com
git config --global user.name 'Andrew Guerrero'
git config --global pull.rebase true
git config --global credential.helper store
