#!/bin/sh

set -ex

yay -S --needed go nerd-fonts-hack tmux ripgrep fd neovim google-chrome nodejs docker steam visual-studio-code-bin cmake
yay -Rsn firefox || true
sudo usermod -aG docker $(whoami)

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
cargo install alacritty starship bottom proximity-sort gitui

git clone https://github.com/alacritty/alacritty.git && cd alacritty && \
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg && \
sudo desktop-file-install extra/linux/Alacritty.desktop && \
sudo update-desktop-database && \
cd .. && rm -rf alacritty 

cp .tmux.conf ~
cp env ~/go
mkdir -p ~/.config/alacritty
cp alacritty.yml ~/.config/alacritty
cp starship.toml ~/.config
mkdir -p ~/.config/nvim
cp init.vim ~/.config/nvim
cp coc-settings.json ~/.config/nvim
cat .bashrc  >> ~/.bashrc
cat .profile >> ~/.profile
cat .bash_profile >> ~/.bash_profile

git config --global init.defaultBranch main
git config --global user.email ajguerrer@gmail.com
git config --global user.name 'Andrew Guerrero'
git config --global pull.rebase true
git config --global credential.helper store
