#!/bin/sh

set -ex

mkdir -p ~/go
cp env ~/go

cp starship.toml ~/.config

mkdir -p ~/.config/nvim
cp init.vim ~/.config/nvim

sed -i '/# AJG/Q' ~/.bashrc
cat .bashrc >> ~/.bashrc

sed -i '/# AJG/Q' ~/.profile
cat .profile >> ~/.profile

git config --global init.defaultBranch main
git config --global user.email ajguerrer@gmail.com
git config --global user.name 'Andrew Guerrero'
git config --global pull.rebase true
git config --global credential.helper store
